add quiet option handling

diff --git a/.script/twitch/twitchscript b/.script/twitch/twitchscript
--- a/.script/twitch/twitchscript
+++ b/.script/twitch/twitchscript
@@ -28,7 +28,7 @@ echoerror () {
 
 aborted () {
     echo "Aborted"
-    exit
+    exit 1
 }
 
 get_user_id () {
@@ -83,7 +83,18 @@ check_and_launch () {
 
     stream_list=$(echo "$twitchdata" | jq -r '.data[] | .language, .user_name' | awk 'NR%2{printf "%s:",$0;next;}1')
     [ -z "$stream_list" ] && echoerror "No streams"
-    stream=$(echo "$stream_list" | $dmenucmd -i -l 10 -p "Which stream ?") || aborted
+
+    if [ -n "$QUIETOPT" ]; then
+        stream_list_bis=$(echo "$stream_list" | awk '{print NR" "$0}')
+        echo "$stream_list_bis"
+        echo ""
+        echo "Choose a stream (number):"
+        read streamnum
+        stream=$(echo "$stream_list_bis" | grep "^$streamnum [a-z][a-z]:.*")
+    else
+        stream=$(echo "$stream_list" | $dmenucmd -i -l 10 -p "Which stream ?") || aborted
+    fi
+
     stream=$(echo "$stream" | sed 's/.*://')
     echo "$stream" > "$laststreamfile"
     exec $chat_command "https://www.twitch.tv/popout/$stream/chat?darkpopout" & mpv "https://www.twitch.tv/$(echo $stream | tr [A-Z] [a-z])"
@@ -92,7 +103,17 @@ check_and_launch () {
 
 twitchgamefunction () {
     laststreamer=$(cat "$laststreamfile")
-    game=$(echo -e "$(cat $gamesfile)\n\nOther\nAdd Game\nAdd last streamer $laststreamer" | $dmenucmd -l 15 -i -p "$noshit") || aborted
+
+    if [ -n "$QUIETOPT" ]; then
+        quietlist=$(cat "$gamesfile" | awk '{print NR" -> "$0}')
+        echo "$quietlist"
+        echo -e "\nChoose a number"
+        read listnum
+        game=$(echo "$quietlist" | grep "^$listnum -> .*" | sed "s/^$listnum -> //")
+    else
+        game=$(echo -e "$(cat $gamesfile)\n\nOther\nAdd Game\nAdd last streamer $laststreamer" | $dmenucmd -l 15 -i -p "$noshit") || aborted
+    fi
+
     if [ "$game" = "Add Game" ]; then
         local dprompt="Which game do you want to add on favorite?"
         game=$($dmenucmd -l 10 -i -p "$dprompt" < "$gamesdb") || aborted
