add tile for game

diff --git a/.script/twitch/twitchscript b/.script/twitch/twitchscript
--- a/.script/twitch/twitchscript
+++ b/.script/twitch/twitchscript
@@ -81,8 +81,7 @@ check_and_launch () {
                       -G "https://api.twitch.tv/helix/streams" \
                       --data-urlencode "game_id=$(get_game_info $game_name)")
 
-    echo "$twitchdata" | jq
-    stream_list=$(echo "$twitchdata" | jq -r '.data[] | .language, .user_name, .title, .viewer_count' | awk '(NR%4==1){lg=$0}(NR%4==2){name=$0}(NR%4==3){title=$0}(NR%4==0){printf "%s:%s %s %s\n",lg,name,title,$0}')
+    stream_list=$(echo "$twitchdata" | jq -r '.data[] | .language, .user_name, .title, .viewer_count' | awk '(NR%4==1){lg=$0}(NR%4==2){name=$0}(NR%4==3){title=$0}(NR%4==0){printf "%s:%s \"%s\" %s\n",lg,name,title,$0}')
     [ -z "$stream_list" ] && echoerror "No streams"
 
     if [ -n "$QUIETOPT" ]; then
@@ -93,11 +92,10 @@ check_and_launch () {
         read streamnum
         stream=$(echo "$stream_list_bis" | grep "^$streamnum [a-z][a-z]:.*")
     else
-        stream=$(echo "$stream_list" | $dmenucmd -i -l 10 -p "Which stream ?") || aborted
+        stream=$(echo "$stream_list" | $dmenucmd -i -l 10 -p "Streams:") || aborted
     fi
 
     stream=$(echo "$stream" | sed 's/.*:\([^ ]*\).*/\1/')
-    echo "$stream"
     echo "$stream" > "$laststreamfile"
     [ -z "$QUIETOPT" ] && exec $chat_command "https://www.twitch.tv/popout/$stream/chat?darkpopout" & mpv "https://www.twitch.tv/$(echo $stream | tr [A-Z] [a-z])"
     exit
