update shits

diff --git a/.script/twitch/twitchscript b/.script/twitch/twitchscript
--- a/.script/twitch/twitchscript
+++ b/.script/twitch/twitchscript
@@ -1,10 +1,13 @@
-#!/bin/bash -i
+#!/bin/bash
 
 # get my private twitch_clientID
 . "${HOME}/.authentification/apikeys.sh"
 
 # colors from wpgtk/pywal
 . "${HOME}/.config/wpg/formats/colors.sh"
+
+. "/home/sam/.authentification/apikeys.sh"
+. "/home/sam/.config/wpg/formats/colors.sh"
 
 # Parameters
 channelsfile=${HOME}/.script/twitch/datas/listchanneltwitch
@@ -25,90 +28,105 @@ aborted(){
 }
 
 check_and_launch(){
-    echo "Checking connected streams for $@ ..."
-    gametocheck=$(echo $@ | sed 's/ /%20/g')
-    twitchdata=$(curl -s 'https://api.twitch.tv/kraken/streams?client_id='$twitch_clientID'&game='$gametocheck)
-    [[ $(echo $twitchdata | jq '._total') == 0 ]] && nobodyshit
-    stream=$(echo $twitchdata | jq -r '.streams[] | .channel.language, .channel.name' | awk 'NR%2{printf "%s:",$0;next;}1' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 10 -p "Which stream ?" | sed 's/.*://')
-    [[ ! -n $stream ]] && aborted
+    echo "Checking connected streams for $* ..."
+    twitchdata=$(curl -s \
+		      -G "https://api.twitch.tv/kraken/streams" \
+		      -d "client_id=$twitch_clientID" \
+		      --data-urlencode "game=$*")
+    [ "$(echo "$twitchdata" | jq '._total')" = 0 ] && nobodyshit
+    stream=$(echo "$twitchdata" | jq -r '.streams[] | .channel.language, .channel.name' | awk 'NR%2{printf "%s:",$0;next;}1' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 10 -p "Which stream ?" | sed 's/.*://')
 
-    exec surf https://www.twitch.tv/popout/$stream/chat?darkpopout & mpv https://www.twitch.tv/$stream
+    [ -z "$stream" ] && aborted
+
+    exec surf "https://www.twitch.tv/popout/$stream/chat?darkpopout" & mpv "https://www.twitch.tv/$stream"
     exit
 }
 
 twitchgamefunction(){        
-    if [[ -n $@ ]]; then
-	check_and_launch $@
-    else	
-	game=$(awk '{print $0} END { printf "Other\nAdd" }' $gamesfile | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "$noshit") || aborted
-	if [[ $game == Add ]];then
-	    game=$(cat $gamesdb | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "Which game do you want to add on favorite?") || aborted
-	    echo -e "$game" >>$gamesfile
-	    cert=$(echo -e "No\nYes" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "Do you want to check streams for $game?")
-	    [[ $cert == Yes ]] || aborted
-	elif [[ $game == Other ]]; then
-	    game=$(cat $gamesdb| dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "$noshit") || aborted
+    if [ -n "$*" ]; then
+	check_and_launch "$*"
+    else
+	game=$(awk '{print $0} END { printf "Other\nAdd" }' "$gamesfile" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "$noshit") || aborted
+	if [ "$game" = "Add" ];then
+	    game=$(dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "Which game do you want to add on favorite?" < "$gamesdb") || aborted
+	    echo "$game" >> "$gamesfile"
+	    cert=$(printf "No\nYes" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "Do you want to check streams for $game?")
+	    [ "$cert" = "Yes" ] || aborted
+	elif [ "$game" = "Other" ]; then
+	    game=$(dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "$noshit" < "$gamesdb") || aborted
 	fi
-	    check_and_launch $game
+	    check_and_launch "$game"
     fi
 }
 
 twitchlivefunction(){
-    if [[ -n $@ ]]; then
-	echo "Checking if $@ is live ..."
-	test=$(curl -s https://api.twitch.tv/kraken/streams/"$@"?client_id=$twitch_clientID | jq ".stream._id")
+    if [ -n "$*" ]; then
+	echo "Checking if $* is live ..."
+	test=$(curl -s \
+		    -G "https://api.twitch.tv/kraken/streams/$*"\
+		    -d "client_id=$twitch_clientID" \
+		   | jq ".stream._id")
 
-	[ ! $test == null ] && (exec surf https://www.twitch.tv/popout/$@/chat?darkpopout & mpv https://www.twitch.tv/"$@") || echo "$@ doesn't stream right now"
+	[ ! "$test" = "null" ] && (exec surf "https://www.twitch.tv/popout/$*/chat?darkpopout" & mpv "https://www.twitch.tv/$*") || echo "$* doesn't stream right now"
 	exit
     else
 	echo "Checking connected streams ..."
-	twitchdata=$(curl -s 'https://api.twitch.tv/kraken/streams?client_id='$twitch_clientID'&channel='$(cat $channelsfile))
+	twitchdata=$(curl -s \
+			  -G "https://api.twitch.tv/kraken/streams" \
+			  -d "client_id=$twitch_clientID" \
+			  -d "channel=$(cat "$channelsfile")")
 
-	stream=$(echo $twitchdata | jq -r '.streams[] | .channel.name' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "Which stream do you want to watch?") || aborted
-	exec surf -new-window https://www.twitch.tv/popout/$stream/chat?darkpopout & mpv https://www.twitch.tv/"$stream"
+	stream=$(echo "$twitchdata" | jq -r '.streams[] | .channel.name' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p "Which stream do you want to watch?") || aborted
+	exec surf -new-window "https://www.twitch.tv/popout/$stream/chat?darkpopout" & mpv "https://www.twitch.tv/$stream"
 	exit
     fi
 }
 
 twitchvod_search(){
-    searchingshit=$(cat $channelsfile | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -p "TwitchVOD Channel:") || aborted
-    echo "Searching for video on "$searchingshit
+    searchingshit=$(dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -p "TwitchVOD Channel:" < "$channelsfile") || aborted
+    printf "Searching for video on %s\n" "$searchingshit"
     curl_choose_and_watch
 }
 
 curl_choose_and_watch(){	
+
     #curl the api twitch vod search for a channel
-    twitchvod=$(curl -s 'https://api.twitch.tv/kraken/channels/'$searchingshit'/videos?client_id='$twitch_clientID'&limit='$max_vid'&offset='$offset)
-    total_vod=$(echo $twitchvod | jq '._total')
-    [[ $total_vod == null || $total_vod == 0 ]] && twitchvod_search
+    twitchvod=$(curl -s \
+		     -G "https://api.twitch.tv/kraken/channels/$searchingshit/videos" \
+ 		     -d "client_id=$twitch_clientID" \
+		     -d "limit=$max_vid" \
+		     -d "offset=$offset" )
+
+    total_vod=$(echo "$twitchvod" | jq '._total')
+    [ "$total_vod" = "null" ] || [ "$total_vod" = 0 ] && twitchvod_search
 
     #create a table with all of the videos and get the url of the chosen one
-    (( borne_max=$total_vod - $max_vid ))
-    video=$(echo $twitchvod | jq -r '.videos[] | .title, .recorded_at' | awk -v bm=$borne_max -v offs=$offset 'BEGIN{ if (offs > 0 ) { printf "Prev\n" } }!(NR%2){printf ("%3d: %-100s %.10s\n", FNR/2+offs, p, $0)}{p=$0}END{ if (offs < bm) { printf "Next" } }' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 30 -p "Which video?" | sed 's/:.*//')
+    : $(( borne_max=total_vod - max_vid ))
+    video=$(echo "$twitchvod" | jq -r '.videos[] | .title, .recorded_at' | awk -v bm=$borne_max -v offs="$offset" 'BEGIN{ if (offs > 0 ) { printf "Prev\n" } }!(NR%2){printf ("%3d: %-100s %.10s\n", FNR/2+offs, p, $0)}{p=$0}END{ if (offs < bm) { printf "Next" } }' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 30 -p "Which video?" | sed 's/:.*//')
 
-    if [[ ! -n $video ]];then
+    if [ -z "$video" ];then
 	twitchvod_search
-    elif [[ $video == Next ]];then
-	((offset= $offset + 100 ))
+    elif [ "$video" = "Next" ];then
+	: $(( offset=offset+100 ))
 	curl_choose_and_watch
-    elif [[ $video == Prev ]];then
-        ((offset= $offset - 100 ))
+    elif [ "$video" = "Prev" ];then
+        : $(( offset=offset-100 ))
 	curl_choose_and_watch
     else	
-	(( num=$video - 1 - $offset))
-	videourl=$(echo $twitchvod | jq -r '.videos['$num'].url')
+	: $(( num=video-1-offset ))
+	videourl=$(echo "$twitchvod" | jq -r '.videos['$num'].url')
 	
 	# ask for the resolution and launch the video with mpv
-	res=$(echo -e "720\n1080\n360" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -p "Which resolution? (if avalaible)") || twitchvod_search
-	mpv --ytdl-format="[height<=?"$res"]" $videourl || twitchvod_search
+	res=$(printf "720\n1080\n360" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -p "Which resolution? (if avalaible)") || twitchvod_search
+	mpv --ytdl-format="[height<=?$res]" "$videourl" || twitchvod_search
 	exit
     fi
 }
 
-if ping -q -c 1 -W 1 1.1.1.1 &>/dev/null; then
+if ping -q -c 1 -W 1 1.1.1.1 >/dev/null 2>&1; then
     case $1 in
 	--live)
-	    twitchlivefunction $2
+	    twitchlivefunction "$2"
 	    ;;
 	--game)
 	    noshit="Choose a game"
@@ -119,7 +137,7 @@ if ping -q -c 1 -W 1 1.1.1.1 &>/dev/null; then
 	    twitchvod_search
 	    ;;
 	*)
-	    echo -e "This is the twitch script featuring dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" and mpv! Heres the options available : \n     --live   To check if your favorites streamers are live\n     --game   To check available streams of a desired game\n     --vod    To check for VOD on a desired channel"
+	    printf "This is the twitch script featuring dmenu and mpv! Heres the options available : \n     --live   To check if your favorites streamers are live\n     --game   To check available streams of a desired game\n     --vod    To check for VOD on a desired channel"
 	    ;;
     esac
 else
diff --git a/.script/youtube/youtubesearch b/.script/youtube/youtubesearch
--- a/.script/youtube/youtubesearch
+++ b/.script/youtube/youtubesearch
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # get my private ytapikey
 . "${HOME}/.authentification/apikeys.sh"
@@ -18,80 +18,82 @@ aborted(){
 
 save_channel(){
     # Save a channel on a rss.org file 
-    check=$(cat $rss_file | grep $channelID)
-    [[ ! -n $check ]] && save_or_not=$(echo -e "No\nYes" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -p "Save this channel ?")
-    [[ $save_or_not == Yes ]] && echo '*** [[https://www.youtube.com/feeds/videos.xml?channel_id='$channelID']['$channame']]' >> $rss_file
+    check=$(grep "$channelID" "$rss_file")
+    [ -z "$check" ] && save_or_not=$(printf "No\nYes" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -p "Save this channel ?")
+    [ "$save_or_not" = "Yes" ] && printf "*** [[https://www.youtube.com/feeds/videos.xml?channel_id=%s][%s]]\n" "$channelID" "$channame" >> "$rss_file"
 }
 
 get_channel_id(){
-    echo $channelname
     channelsearch=$(curl -s \
 			 -G https://www.googleapis.com/youtube/v3/search \
-			 --data-urlencode 'q='"'$channelname'"'' \
-			 -d 'type=channel' \
-			 -d 'maxResults=25' \
-			 -d 'part=snippet' \
-			 -d 'key='$ytapikey'')
-    echo $channelsearch | jq
-    chanchoice=$(echo $channelsearch | jq -r '.items[] | .snippet.channelTitle' | awk '{printf ("%2d: %s\n",NR,$0)}' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p 'Which channel ?')
-    channame=$(echo $chanchoice | sed 's/.*: //')
-    chanchoice=$(echo $chanchoice | sed 's/:.*//')
-    [[ ! -n $chanchoice ]] && youtube_search
-    (( numchan= $chanchoice - 1 ))
-    channelID=$(echo $channelsearch | jq -r '.items['$numchan'].snippet.channelId')
+			 --data-urlencode "q=$channelname" \
+			 -d "type=channel" \
+			 -d "maxResults=25" \
+			 -d "part=snippet" \
+			 -d "key=$ytapikey")
+    
+    chanchoice=$(echo "$channelsearch" | jq -r '.items[] | .snippet.channelTitle' | awk '{printf ("%2d: %s\n",NR,$0)}' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 10 -i -p 'Which channel ?')
+    channame=$(echo "$chanchoice" | sed 's/.*: //')
+    chanchoice=$(echo "$chanchoice" | sed 's/:.*//')
+    [ -z "$chanchoice" ] && youtube_search
+    : $(( numchan=chanchoice-1 ))
+    channelID=$(echo "$channelsearch" | jq -r '.items['$numchan'].snippet.channelId')
 }
 
 youtube_search(){
     channelID=""
-    searchingshit=$(tail -n 1 $searchhistory | awk '{print$0}END{printf "\nShow History\nChannel option"}' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 20 -p "Youtube search:") || aborted
-    if [[ $searchingshit == 'Channel option' ]];then
+    searchingshit=$(tail -n 1 "$searchhistory" | awk '{print$0}END{printf "\nShow History\nChannel option"}' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 20 -p "Youtube search:") || aborted
+    if [ "$searchingshit" = "Channel option" ];then
 	channelname=$(echo | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -p "Channel Search") || youtube_search
         get_channel_id
 	save_channel
 	
 	searchingshit=$(echo | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 20 -p "Search on this channel:") || youtube_search
-    elif [[ $searchingshit == 'Show History' ]];then
-	     searchingshit=$(cat $searchhistory | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 20 -p "Search in History:") || youtube_search
+    elif [ "$searchingshit" = "Show History" ];then
+	     searchingshit=$(dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -l 20 -p "Search in History:" < "$searchhistory") || youtube_search
     else
-	echo $searchingshit >> $searchhistory
-	echo "Searching for "$searchingshit
+	echo "$searchingshit" >> "$searchhistory"
+	printf "Searching for %s\n" "$searchingshit"
     fi
 
-    if [[ ! -n $channelID ]] ; then
+    if [ -z "$channelID" ] ; then
 	youtubesearchdata=$(curl -s \
 				 -G https://www.googleapis.com/youtube/v3/search \
-				 -d 'type=video' \
-				 -d 'maxResults='$max_results'' \
-				 -d 'key='$ytapikey'' \
-				 -d 'order=date' \
-				 -d 'part=snippet' \
-				 --data-urlencode 'q='"'$searchingshit'"''
+				 -d "type=video" \
+				 -d "maxResults=$max_results" \
+				 -d "key=$ytapikey" \
+				 -d "order=date" \
+				 -d "part=snippet" \
+				 --data-urlencode "q=$searchingshit"
 				 )
     else
 	youtubesearchdata=$(curl -s \
 				 -G https://www.googleapis.com/youtube/v3/search \
-				 -d 'type=video' \
-				 -d 'order=date' \
-				 -d 'maxResults='$max_results'' \
-				 -d 'key='$ytapikey'' \
-				 -d 'part=snippet' \
-				 -d 'channelId='$channelID''
+				 -d "type=video" \
+				 -d "order=date" \
+				 -d "maxResults=$max_results" \
+				 -d "key=$ytapikey" \
+				 -d "part=snippet" \
+				 -d "channelId=$channelID" \
+				 --data-urlencode "q=$searchingshit"
 				 )
     fi
-    video=$(echo $youtubesearchdata | jq -r '.items[] | .snippet.title, .snippet.channelTitle, .snippet.publishedAt' | awk '{printf ("%.85s\n",$0)}' | awk '(NR%3==1){name=$0}(NR%3==2){date=$0}(NR%3==0){printf ("%2d: %-85s %-20s %.10s \n", NR/3, name, date, $0)}' | sed 's/|//g' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 30 -i -p 'YTSearch' | sed 's/:.*//')
-    [[ ! -n $video ]] && youtube_search
-    (( num= $video - 1 ))
-    videoID=$(echo $youtubesearchdata | jq -r '.items['$num'].id.videoId')
+    video=$(echo "$youtubesearchdata" | jq -r '.items[] | .snippet.title, .snippet.channelTitle, .snippet.publishedAt' | awk '{printf ("%.85s\n",$0)}' | awk '(NR%3==1){name=$0}(NR%3==2){date=$0}(NR%3==0){printf ("%2d: %-85s %-20s %.10s \n", NR/3, name, date, $0)}' | sed 's/|//g' | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -l 30 -i -p 'YTSearch' | sed 's/:.*//')
+    [ -z "$video" ] && youtube_search
 
-    printf 'https://www.youtube.com/watch?v='$videoID | xclip -selection clipboard # clipboard to share with your friend !
+    : $(( num= video - 1 ))
 
-    res=$(echo -e "720\n1080\n360" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -p "Which resolution? (if avalaible)") || youtube_search
-    
-    mpv --ytdl-format="[height<=?"$res"]" 'https://www.youtube.com/watch?v='$videoID    
+    videoID=$(echo "$youtubesearchdata" | jq -r '.items['$num'].id.videoId')
+
+    printf "https://www.youtube.com/watch?v=%s" "$videoID" | xclip -selection clipboard # clipboard to share with your friend !
+
+    res=$(printf "720\n1080\n360" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -i -p "Which resolution? (if avalaible)") || youtube_search
+
+    mpv --ytdl-format="[height<=?$res]" "https://www.youtube.com/watch?v=$videoID"
     exit
 }
 
-if ping -q -c 1 -W 1 1.1.1.1 &>/dev/null; then
+if ping -q -c 1 -W 1 1.1.1.1 >/dev/null 2>&1; then
     youtube_search
 else
     notify-send "No internet connection"
