minor improvments

diff --git a/.script/twitch/twitchscript b/.script/twitch/twitchscript
--- a/.script/twitch/twitchscript
+++ b/.script/twitch/twitchscript
@@ -16,8 +16,11 @@ chat_command="brave -new-window"
 
 max_vid=100
 
-[ -n "$QUIETOPT" ] && menucmd="fzfcmd" || menucmd="dmenu -nb $color0 -nf $color15 -sb $color0 -sf $color3"
-
+if [ -n "$QUIETOPT" ]; then
+    menucmd="fzfcmd"
+else
+    menucmd="dmenu -nb $color0 -nf $color15 -sb $color0 -sf $color3"
+fi
 
 touch "$laststreamfile"
 
@@ -35,24 +38,24 @@ fzfcmd(){
     fzf --prompt="$prompt" "$iflag"
 }
 
-echoerror () {
+echoerror() {
     echo "$*"
     noshit="$*. Choose an other game:"
     twitchgamefunction
 }
 
-aborted () {
+aborted() {
     [ -n "$1" ] && echo "Error: $1"
-    echo "Aborted"
     exit 1
 }
 
 check_internet() {
-    echo bite
-    # ! ping -q -c 1 -W 1 1.1.1.1 >/dev/null 2>&1 && aborted "No internet connection"
+    if ! ping -q -c 1 -W 1 1.1.1.1 >/dev/null 2>&1; then
+        aborted "No internet connection"
+    fi
 }
 
-get_user_id () {
+get_user_id() {
     input="$*"
     if echo "$input" | grep -q "^[0-9]*$";then
         curl_data=$(curl -s \
@@ -71,7 +74,6 @@ get_user_id () {
     fi
     [ -n "$output" ] && echo "$output" || aborted "Nothing found for $*"
 }
-
 
 get_game_info () {
     input="$*"
@@ -105,7 +107,7 @@ check_and_launch () {
     stream_list=$(echo "$twitchdata" | sed 's/\\n//g' | jq -r '.data[] | .language, .user_name, .title, .viewer_count' | awk '(NR%4==1){lg=$0}(NR%4==2){name=$0}(NR%4==3){title=$0}(NR%4==0){printf "%s:%s \"%s\" %s\n",lg,name,title,$0}')
     [ -z "$stream_list" ] && echoerror "No streams"
 
-    stream=$(echo "$stream_list" | $menucmd -i -l 10 -p "Streams:") || aborted
+    stream=$(echo "$stream_list" | $menucmd -i -l 10 -p "Streams: ") || aborted
 
     stream=$(echo "$stream" | sed 's/.*:\([^ ]*\).*/\1/')
     echo "$stream" > "$laststreamfile"
@@ -122,7 +124,7 @@ twitchgamefunction () {
             game=$($menucmd -l 10 -i -p "$dprompt" < "$gamesdb") || aborted
             echo "$game" >> "$gamesfile"
 
-            local dprompt="Do you want to check streams for $game?"
+            local dprompt="Do you want to check streams for $game? "
             cert=$(printf "No\nYes" | $menucmd -l 10 -i -p "$dprompt")
             [ "$cert" = "Yes" ] || aborted
             ;;
@@ -170,7 +172,7 @@ twitchlivefunction () {
 }
 
 twitchvod_search(){
-    searchingshit=$(sort "$channelsfile" | $menucmd -l 10 -p "TwitchVOD Channel:") || aborted
+    searchingshit=$(sort "$channelsfile" | $menucmd -l 10 -p "TwitchVOD Channel: ") || aborted
     printf "Searching for video on %s\n" "$searchingshit"
     curl_choose_and_watch
 }
@@ -189,7 +191,7 @@ curl_choose_and_watch(){
 
     #create a table with all of the videos and get the url of the chosen one
     : $(( borne_max=total_vod - max_vid ))
-    video=$(echo "$twitchvod" | jq -r '.data[] | .title, .created_at' | awk -v bm=$borne_max -v offs="$offset" 'BEGIN{ if (offs > 0 ) { printf "Prev\n" } }!(NR%2){printf ("%3d: %-100s %.10s\n", FNR/2+offs, p, $0)}{p=$0}END{ if (offs < bm) { printf "Next" } }' | $menucmd -i -l 30 -p "Which video?" | sed 's/:.*//')
+    video=$(echo "$twitchvod" | jq -r '.data[] | .title, .created_at' | awk -v bm=$borne_max -v offs="$offset" 'BEGIN{ if (offs > 0 ) { printf "Prev\n" } }!(NR%2){printf ("%3d: %-100s %.10s\n", FNR/2+offs, p, $0)}{p=$0}END{ if (offs < bm) { printf "Next" } }' | $menucmd -i -l 30 -p "Which video: " | sed 's/:.*//')
 
     if [ -z "$video" ];then
         twitchvod_search
@@ -204,7 +206,7 @@ curl_choose_and_watch(){
         videourl=$(echo "$twitchvod" | jq -r '.data['$num'].url')
 
         # ask for the resolution and launch the video with mpv
-        res=$(printf "720\n1080\n360" | $menucmd -i -p "Which resolution? (if avalaible)") || twitchvod_search
+        res=$(printf "720\n1080\n360" | $menucmd -i -p "Which resolution? (if avalaible): ") || twitchvod_search
         mpv --ytdl-format="[height<=?$res]" "$videourl" || twitchvod_search
         exit
     fi
@@ -220,9 +222,16 @@ twitchmenu() {
     choice=$(printf "LIVE\nGAMES\nVOD\n\nAdd last streamer: $laststreamer\nDelete streamer" | $menucmd -i -l 10 -p "Twitch Menu :")
 
     case "$choice" in
-        "LIVE") "${HOME}"/.script/twitch/twitchscript --live ;;
-        "GAMES") "${HOME}"/.script/twitch/twitchscript --game ;;
-        "VOD") "${HOME}"/.script/twitch/twitchscript --vod ;;
+        "LIVE")
+        twitchlivefunction "$2" ;;
+        "GAMES")
+            args=$(echo "$*" | sed "s/$1 *//")
+            noshit="Choose a game: "
+            [ -n "$args" ] && check_and_launch "$args"
+            twitchgamefunction ;;
+        "VOD")
+            offset=0
+            twitchvod_search ;;
         "Add last streamer: $laststreamer") cat "$laststreamfile" >> "$channelsfile" ;;
         "Delete streamer") delete_streamer ;;
         *) aborted ;;
